language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t dsengupta50/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dsengupta50/docker-react npm run test